export const FETCH_CURRENT_WEATHER = 'FETCH_CURRENT_WEATHER';
export const DONE_FETCHING_CURRENT_WEATHER = 'DONE_FETCHING_CURRENT_WEATHER';
export const DONE_FETCHING_FORECAST = 'DONE_FETCHING_FORECAST';
export const FETCH_FORECAST = 'FETCH_FORECAST';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const ERROR_FETCHING_CURRENT_WEATHER = 'ERROR_FETCHING_CURRENT_WEATHER';
export const ERROR_FETCHING_FORECAST = 'ERROR_FETCHING_FORECAST';
